name: Build Image and Push to Github Package
on:
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v3.0
      with:
        image: supakornbabe/spai-race-detection
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
